DROP TRIGGER IF EXISTS NIFUnicoCliente;
DROP TRIGGER IF EXISTS NIFUnicoMedico;
DROP TRIGGER IF EXISTS NIFUnicoOutro;

CREATE TRIGGER NIFUnicoCliente
BEFORE INSERT 
ON Cliente
WHEN NEW.NIF IN (SELECT NIF FROM Medico UNION SELECT NIF FROM Outro)
BEGIN
SELECT raise(rollback, 'NIF nao unico');
END;

CREATE TRIGGER NIFUnicoMedico
BEFORE INSERT 
ON Medico
WHEN NEW.NIF IN (SELECT NIF FROM Cliente UNION SELECT NIF FROM Outro)
BEGIN
SELECT raise(rollback, 'NIF nao unico');
END;

CREATE TRIGGER NIFUnicoOutro
BEFORE INSERT 
ON Outro
WHEN NEW.NIF IN (SELECT NIF FROM Cliente UNION SELECT NIF FROM Medico)
BEGIN
SELECT raise(rollback, 'NIF nao unico');
END